import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Children } from "react";
import Footer from "@/components/footer";


const inter = Inter({ subsets: ["latin"] });
const lato = Lato({subsets:["latin"],weight:["400"]});

export const metadata: Metadata = {
  title: "Paragon Oak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Navbar/>
        {children}
        <Footer/>
        <script src="../path/to/flowbite/dist/flowbite.min.js" async/>
        </body>
    </html>
  );
}
